export const LIMITS = {
  MAX_IMAGE_BYTES: 10 * 1024 * 1024,
  MAX_IMAGE_BYTES_LABEL: '10 MB',
  MAX_HISTORY_PER_USER: 50,
  FREE_DAILY_ANALYSES: 3,
  PRO_DAILY_ANALYSES: Number.POSITIVE_INFINITY,
  TEAM_DAILY_ANALYSES: Number.POSITIVE_INFINITY,
  TEAM_MAX_USERS: 5,
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 128,
  EMAIL_MAX_LENGTH: 254,
  ACCESS_TOKEN_TTL_SECONDS: 60 * 15,
  REFRESH_TOKEN_TTL_SECONDS: 60 * 60 * 24 * 30,
  CLAUDE_MAX_TOKENS: 2048,
  THROTTLE_TTL_SECONDS: 60,
  THROTTLE_LIMIT_PER_MIN: 30,
} as const;

export const PRICING = {
  FREE_USD_PER_MONTH: 0,
  PRO_USD_PER_MONTH: 19,
  TEAM_USD_PER_MONTH: 49,
} as const;
